FROM node

RUN mkdir /src

WORKDIR /src

# CMD node server.js
CMD npm start

# docker run -p 3001:80  -v /Users/appdev/Documents/ds/system-management-project-BackEnd/:/src  --name ds-backend-dev  ds-backend-dev 